"""empty message

Revision ID: 1aba17591fa2
Revises: f75796f73952
Create Date: 2017-11-09 20:26:28.155729

"""

# revision identifiers, used by Alembic.
revision = '1aba17591fa2'
down_revision = 'f75796f73952'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_analytics', sa.Column('escore', sa.Float(), nullable=True))
    op.add_column('asin_analytics', sa.Column('streak_score_v1', sa.Float(), nullable=True))
    op.add_column('asin_analytics', sa.Column('streak_score_v2', sa.Float(), nullable=True))
    op.add_column('asin_analytics', sa.Column('weighted_escore_v1', sa.Float(), nullable=True))
    op.add_column('asin_analytics', sa.Column('weighted_escore_v2', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_analytics', 'weighted_escore_v2')
    op.drop_column('asin_analytics', 'weighted_escore_v1')
    op.drop_column('asin_analytics', 'streak_score_v2')
    op.drop_column('asin_analytics', 'streak_score_v1')
    op.drop_column('asin_analytics', 'escore')
    ### end Alembic commands ###
