"""empty message

Revision ID: 2f07293003ce
Revises: 00bb44b8e07b
Create Date: 2017-12-08 22:18:10.169160

"""

# revision identifiers, used by Alembic.
revision = '2f07293003ce'
down_revision = '00bb44b8e07b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('discovery_timestamp', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'discovery_timestamp')
    ### end Alembic commands ###
