"""empty message

Revision ID: 320016755a31
Revises: 6a8f0b9d7d77
Create Date: 2017-10-14 18:49:15.679296

"""

# revision identifiers, used by Alembic.
revision = '320016755a31'
down_revision = '6a8f0b9d7d77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('browse_node', sa.String(), nullable=True))
    op.add_column('asin_metadata', sa.Column('search_index', sa.String(), nullable=True))
    op.drop_column('asin_metadata', 'asin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('asin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('asin_metadata', 'search_index')
    op.drop_column('asin_metadata', 'browse_node')
    ### end Alembic commands ###
