"""empty message

Revision ID: 3b51eb05f42e
Revises: e28f13c95e0d
Create Date: 2018-01-12 17:59:08.326748

"""

# revision identifiers, used by Alembic.
revision = '3b51eb05f42e'
down_revision = 'e28f13c95e0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('escore', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_1mo_list_price', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_1mo_salesrank', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_1mo_volatility', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_3mo_list_price', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_3mo_salesrank', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_3mo_volatility', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_7d_list_price', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_7d_salesrank', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('last_7d_volatility', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('list_price', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('streak_score_v1', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('streak_score_v2', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('weighted_escore_v1', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('weighted_escore_v2', sa.Float(), nullable=True))
    op.add_column('asin_metadata', sa.Column('weighted_escore_v3', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'weighted_escore_v3')
    op.drop_column('asin_metadata', 'weighted_escore_v2')
    op.drop_column('asin_metadata', 'weighted_escore_v1')
    op.drop_column('asin_metadata', 'streak_score_v2')
    op.drop_column('asin_metadata', 'streak_score_v1')
    op.drop_column('asin_metadata', 'list_price')
    op.drop_column('asin_metadata', 'last_7d_volatility')
    op.drop_column('asin_metadata', 'last_7d_salesrank')
    op.drop_column('asin_metadata', 'last_7d_list_price')
    op.drop_column('asin_metadata', 'last_3mo_volatility')
    op.drop_column('asin_metadata', 'last_3mo_salesrank')
    op.drop_column('asin_metadata', 'last_3mo_list_price')
    op.drop_column('asin_metadata', 'last_1mo_volatility')
    op.drop_column('asin_metadata', 'last_1mo_salesrank')
    op.drop_column('asin_metadata', 'last_1mo_list_price')
    op.drop_column('asin_metadata', 'escore')
    ### end Alembic commands ###
