"""empty message

Revision ID: 676d3a084099
Revises: c6bded3f1c05
Create Date: 2017-12-21 18:24:55.470585

"""

# revision identifiers, used by Alembic.
revision = '676d3a084099'
down_revision = 'c6bded3f1c05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('removed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'removed')
    ### end Alembic commands ###
