"""empty message

Revision ID: 6a8f0b9d7d77
Revises: ae99e44fbb08
Create Date: 2017-10-14 15:48:38.520050

"""

# revision identifiers, used by Alembic.
revision = '6a8f0b9d7d77'
down_revision = 'ae99e44fbb08'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'currency')
    op.drop_column('asin_metadata', 'main_salesrank')
    op.drop_column('asin_metadata', 'list_price')
    op.drop_column('asin_metadata', 'main_category_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('main_category_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asin_metadata', sa.Column('list_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('asin_metadata', sa.Column('main_salesrank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('asin_metadata', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
