"""empty message

Revision ID: 7ef60a8e5af8
Revises: 676d3a084099
Create Date: 2018-01-12 01:30:16.643876

"""

# revision identifiers, used by Alembic.
revision = '7ef60a8e5af8'
down_revision = '676d3a084099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('asin_salesrank', sa.Integer(), nullable=True))
    op.add_column('asin_metadata', sa.Column('asin_unthrottled_salesrank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'asin_unthrottled_salesrank')
    op.drop_column('asin_metadata', 'asin_salesrank')
    ### end Alembic commands ###
