"""empty message

Revision ID: 7f704e8b7a9a
Revises: e285142613f3
Create Date: 2017-11-14 19:29:39.530948

"""

# revision identifiers, used by Alembic.
revision = '7f704e8b7a9a'
down_revision = 'e285142613f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_query', sa.Column('user_object_id', sa.String(), nullable=True))
    op.add_column('user_query', sa.Column('username', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_query', 'username')
    op.drop_column('user_query', 'user_object_id')
    ### end Alembic commands ###
