"""empty message

Revision ID: aa92f29c3293
Revises: 1aba17591fa2
Create Date: 2017-11-10 00:07:16.370430

"""

# revision identifiers, used by Alembic.
revision = 'aa92f29c3293'
down_revision = '1aba17591fa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_analytics', sa.Column('weighted_escore_v3', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_analytics', 'weighted_escore_v3')
    ### end Alembic commands ###
