"""empty message

Revision ID: ae99e44fbb08
Revises: None
Create Date: 2017-10-14 15:22:07.206421

"""

# revision identifiers, used by Alembic.
revision = 'ae99e44fbb08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asin_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('parent_asin', sa.String(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('studio', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('binding', sa.String(), nullable=True),
    sa.Column('product_group', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('product_type_name', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('marketplace_id', sa.String(), nullable=True),
    sa.Column('main_category_id', sa.String(), nullable=True),
    sa.Column('main_salesrank', sa.Integer(), nullable=True),
    sa.Column('discovery_keyword', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asin_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('salesrank', sa.Integer(), nullable=True),
    sa.Column('salesrank_category', sa.String(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indexed_keyword',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_indexed_date', sa.String(), nullable=True),
    sa.Column('number_of_times_indexed', sa.Integer(), nullable=True),
    sa.Column('first_indexed_date', sa.String(), nullable=True),
    sa.Column('number_of_merch_shirts_found', sa.Integer(), nullable=True),
    sa.Column('average_salesrank_of_shirts_found', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexed_keyword')
    op.drop_table('asin_snapshot')
    op.drop_table('asin_metadata')
    ### end Alembic commands ###
