"""empty message

Revision ID: c6bded3f1c05
Revises: 2f07293003ce
Create Date: 2017-12-12 21:04:10.887240

"""

# revision identifiers, used by Alembic.
revision = 'c6bded3f1c05'
down_revision = '2f07293003ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_analytics', sa.Column('unthrottled_salesrank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_analytics', 'unthrottled_salesrank')
    ### end Alembic commands ###
