"""empty message

Revision ID: e12ccf3dbb2e
Revises: 7f704e8b7a9a
Create Date: 2017-11-16 18:10:04.628478

"""

# revision identifiers, used by Alembic.
revision = 'e12ccf3dbb2e'
down_revision = '7f704e8b7a9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('last_trademark_indexed_date', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'last_trademark_indexed_date')
    ### end Alembic commands ###
