"""empty message

Revision ID: e285142613f3
Revises: aa92f29c3293
Create Date: 2017-11-14 19:23:23.183136

"""

# revision identifiers, used by Alembic.
revision = 'e285142613f3'
down_revision = 'aa92f29c3293'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('number_of_merch_shirts_found', sa.Integer(), nullable=True),
    sa.Column('average_salesrank', sa.Float(), nullable=True),
    sa.Column('lowest_salesrank', sa.Float(), nullable=True),
    sa.Column('bottom_tenth_percentile_salesrank', sa.Float(), nullable=True),
    sa.Column('average_list_price', sa.Float(), nullable=True),
    sa.Column('lowest_price', sa.Float(), nullable=True),
    sa.Column('highest_price', sa.Float(), nullable=True),
    sa.Column('best_product_image', sa.String(), nullable=True),
    sa.Column('best_product_title', sa.String(), nullable=True),
    sa.Column('best_product_brand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_query')
    ### end Alembic commands ###
