"""empty message

Revision ID: e28f13c95e0d
Revises: 7ef60a8e5af8
Create Date: 2018-01-12 13:40:20.054895

"""

# revision identifiers, used by Alembic.
revision = 'e28f13c95e0d'
down_revision = '7ef60a8e5af8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_metadata', sa.Column('asin_list_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_metadata', 'asin_list_price')
    ### end Alembic commands ###
