"""empty message

Revision ID: f338647d8843
Revises: 320016755a31
Create Date: 2017-10-16 22:59:38.644528

"""

# revision identifiers, used by Alembic.
revision = 'f338647d8843'
down_revision = '320016755a31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asin_snapshot', sa.Column('currency_code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asin_snapshot', 'currency_code')
    ### end Alembic commands ###
