"""empty message

Revision ID: f75796f73952
Revises: f338647d8843
Create Date: 2017-10-21 22:15:28.701926

"""

# revision identifiers, used by Alembic.
revision = 'f75796f73952'
down_revision = 'f338647d8843'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asin_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_indexed_date', sa.String(), nullable=True),
    sa.Column('salesrank', sa.Integer(), nullable=True),
    sa.Column('last_7d_salesrank', sa.Float(), nullable=True),
    sa.Column('last_1mo_salesrank', sa.Float(), nullable=True),
    sa.Column('last_3mo_salesrank', sa.Float(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('last_7d_list_price', sa.Float(), nullable=True),
    sa.Column('last_1mo_list_price', sa.Float(), nullable=True),
    sa.Column('last_3mo_list_price', sa.Float(), nullable=True),
    sa.Column('last_7d_volatility', sa.Float(), nullable=True),
    sa.Column('last_1mo_volatility', sa.Float(), nullable=True),
    sa.Column('last_3mo_volatility', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asin_analytics')
    ### end Alembic commands ###
